# Lifecycle latency report

Generated by `tools/perf/lifecycle-report.sh`. The numbers are the measured
distribution of the published benchmark, not a target: what a release claims is
that a lifecycle of this shape costs this much on a host like this one.

## Host

| | |
|---|---|
| measured | %GENERATED% |
| kernel | %KERNEL% |
| cpu | %CPU% |
| load | %LOAD% (1-minute average / CPUs) |
| filesystem | %FILESYSTEM% |
| rust | %RUST% |
| binary | %BINARY% |
| up workers | %WORKERS% |
| fixture | %FIXTURE% |
| cycles | %ITERATIONS% (1 cold + %WARM_CYCLES% warm) |

Provenance: %PROVENANCE%.

## Warm tier

The warm tier is every cycle after the first, which is the steady state a
workspace sees once its rootfs is in the page cache. The cold cycle is reported
on its own because it pays for filling that cache, and one number covering both
would describe neither.

| phase | p50 | p95 | p99 | max |
|---|---|---|---|---|
| workspace boot | %BOOT_P50%s | %BOOT_P95%s | %BOOT_P99%s | %BOOT_MAX%s |
| sandbox shutdown | %STOP_P50%s | %STOP_P95%s | %STOP_P99%s | %STOP_MAX%s |

Cold tier, first cycle only:

| phase | seconds |
|---|---|
| workspace boot | %BOOT_COLD% |
| sandbox shutdown | %SHUTDOWN_COLD% |

## Raw samples

Every sample is kept so a percentile can be re-derived rather than only read.

```
boot_seconds = %BOOT_RAW%
shutdown_seconds = %STOP_RAW%
```

## Reproducing

```bash
ENCLAVE_LIVE_ITERATIONS=%ITERATIONS% ./tools/perf/lifecycle-report.sh
```

This needs a privileged host with a cached rootfs at `%ROOTFS%` and runs against
a daemon it starts in its own state directory, so it does not touch a sandbox
that is already running.
